# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9952f1a111b1e074dcc92258da497121babf5ec1da465afd2b5a1c9ea580abbdc54f9b3adac038eb3f612f385c82c986110419f30dbab310e2bd76b9e1fb9b99

test:
  secret_key_base: b76428599bfcaf8f6ee2674fc3630b8d9b8166a5d67d15dbd07af248c3f81a8f93978d2790c5253e0fb608dc73dac4c5437ec1a58bff3474a51c93e150ba48e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
